name: Notify Slack Action
description: Notifies slack about the results of a given workflow
author: Will McGinty

inputs:
  webhook_url:
    description: The webhook URL used to communicate with Slack.
    required: true
  success:
    description: A boolean describing whether the job succeeded
    required: true
    default: true
  artifacts_url:
    description: The URL at which any artifacts for the job reside
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      id: prepare_payload
      run: |
        ### Determine the build result ###
        if [[ ${{ inputs.success }} == true ]]; then
          build_result=":white_check_mark: Build Success"
        else
          build_result=":red_circle: Build Failure"
        fi

        ### Determine the short version of the commit hash ###
        short_hash=$(echo "${{ github.sha }}" | cut -c 1-10)

        ### Determine the payload fields based on the present of artifact URL ###
        artifacts_payload_field=""
        if [[ -n "${{ inputs.artifacts_url }}" ]]; then
          artifacts_payload_field=", { \"type\": \"mrkdwn\", \"text\": \"*Artifacts:* <${{ inputs.artifacts_url }}|View>\" }"
        fi

        ### Construct the payload JSON and write it to a file ###
        cat > payload-content.json <<EOF
        {
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "$build_result",
                "emoji": true
              }
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Branch:* ${{ github.ref_name }}"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Build:* ${{ github.run_number }}"
                }
                $artifacts_payload_field,
                {
                  "type": "mrkdwn",
                  "text": "*Log:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View>"
                }
              ]
            },
            {
              "type": "divider"
            },
            {
              "type": "context",
              "elements": [
                {
                  "type": "mrkdwn",
                  "text": "*Author:* ${{ github.actor }}"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Commit Hash:* $short_hash"
                }
              ]
            }
          ]
        }
        EOF

        ### Validate the JSON ###
        jq empty payload-content.json

    - id: send
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload-file-path: "./payload-content.json"
  
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK  
