name: Test
on: [push, pull_request]
jobs:
  test_slack:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Success
        uses: ./
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          success: true
          artifacts_url: https://www.apple.com

      - name: Test No Artifacts
        uses: ./
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          success: true

      - name: Test Failure
        uses: ./
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          success: false
          artifacts_url: https://www.google.com

