name: Test
on: [push, pull_request]
jobs:
  test_transfer_defaults:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Success
        uses: ./
        with:
          success: true
          artifacts_url: https://www.apple.com

      - name: Test Failure
        uses: ./
        with:
          success: false
          artifacts_url: https://www.google.com

